### ISSUE TITLE
Move command fails for non-existing shellcut

### ISSUE THREAD

**Issue by tigressine** [tgsachse/shellcuts#58]
Traceback (most recent call last):
  File "/home/tgsachse/.shellcuts/source/shellcuts.py", line 43, in <module>
    commander.execute(parser.arguments)
  File "/home/tgsachse/.shellcuts/source/core/commander.py", line 37, in execute
    self.move(arguments.move)
  File "/home/tgsachse/.shellcuts/source/core/commander.py", line 106, in move
    self.shellcuts[name][utilities.PATH] = os.getcwd()
TypeError: 'NoneType' object does not support item assignment

**Comment by tigressine** [comment]
Irrelevant because the project is being rewritten.
