### ISSUE TITLE
`python3 install.py` fails

### ISSUE THREAD

**Issue by excursus** [tgsachse/shellcuts#81]
I think the install script assumes the existence of the `~/.shellcuts` directory. Creating this directory seems to fix the install.
```
Beginning installation.
Removing old installations...
Traceback (most recent call last):
  File "install.py", line 67, in <module>
    shutil.rmtree(str(DESTINATION_DIRS['shellcuts']))
  File "/usr/local/Cellar/python@3.8/3.8.3_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 706, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/local/Cellar/python@3.8/3.8.3_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 704, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/<user>/.shellcuts'
```

**Comment by tigressine** [comment]
Hey, thanks for opening these. I'm currently almost finished rewriting this project in Scala, and the new installation process is a lot simpler.

Once I release the new version (you can see progress on the mainline/ branch) I will resolve this issue.
